apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'


android {
    compileSdkVersion 36

    defaultConfig {
        applicationId "com.ttpCorp.carlosguzman.gasolinamexico"
        minSdkVersion 21
        targetSdkVersion 36
        versionCode 25
        versionName "2.5.0"
        vectorDrawables.useSupportLibrary = true
    }
    buildTypes {
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            buildConfigField "String", "BASE_URL", "\"file:///android_asset/dist/index.html\""
            buildConfigField "String", "ADMOB_BANNER_ID", "\"ca-app-pub-3904073734017654/6308546110\"" // ID de prueba oficial de Google
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            buildConfigField "String", "BASE_URL", "\"file:///android_asset/dist/index.html\""
            buildConfigField "String", "ADMOB_BANNER_ID", "\"ca-app-pub-3403038737253823/COLOCA_AQUI_TU_BANNER_ID_REAL\"" // Reemplazar con tu ID de bloque de anuncios de AdMob
        }
    }
    buildFeatures {
        buildConfig = true
    }
    namespace 'com.ttpCorp.carlosguzman.preciogasolinamexico'
}
repositories {
    google()
    mavenCentral()
    maven { url "https://jitpack.io" }
}
dependencies {


    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'com.github.PhilJay:MPAndroidChart:v2.1.6'
    implementation platform('com.google.firebase:firebase-bom:33.7.0') // Existing BoM
    implementation 'com.google.firebase:firebase-analytics-ktx' // Includes firebase-core
    implementation 'com.google.firebase:firebase-messaging-ktx'
    implementation 'com.google.android.gms:play-services-ads:23.6.0'
    implementation 'com.google.firebase:firebase-config'
    implementation 'androidx.work:work-runtime:2.9.0'
    implementation 'androidx.webkit:webkit:1.12.0'
    implementation 'androidx.vectordrawable:vectordrawable:1.1.0'
}
