apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'


android {
    compileSdkVersion 34

    defaultConfig {
        applicationId "com.ttpCorp.carlosguzman.gasolinamexico"
        minSdkVersion 21
        targetSdkVersion 35
        versionCode 23
        versionName "Android X"
        vectorDrawables.useSupportLibrary = true
    }
    buildTypes {
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            buildConfigField "String", "BASE_URL", "\"http://45.132.241.215:8888/gasolinamexico/dev/UI/dist/index.html\""
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            buildConfigField "String", "BASE_URL", "\"http://45.132.241.215:8888/gasolinamexico/prod/UI/dist/index.html\""
        }
    }
    buildFeatures {
        buildConfig = true
    }
    namespace 'com.ttpCorp.carlosguzman.preciogasolinamexico'
}
repositories {
    google()
    mavenCentral()
    maven { url "https://jitpack.io" }
}
dependencies {


    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'com.github.PhilJay:MPAndroidChart:v2.1.6'
    implementation platform('com.google.firebase:firebase-bom:32.7.0') // Existing BoM
    implementation 'com.google.firebase:firebase-analytics-ktx' // Includes firebase-core
    implementation 'com.google.firebase:firebase-messaging-ktx'
    implementation 'com.google.android.gms:play-services-ads:23.0.0'
    implementation 'com.google.firebase:firebase-config'
    implementation 'androidx.vectordrawable:vectordrawable:1.1.0'
}
